apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: block-copyfail

resources:
  - bc-block-copyfail.yaml
  - ds-block-copyfail.yaml
  - is-copyfail.yaml
  - is-ubi.yaml
  - namespace.yaml
  - rbac.yaml
