---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: block-copyfail
    app.kubernetes.io/component: block-copyfail
    app.kubernetes.io/instance: block-copyfail
    app.kubernetes.io/name: block-copyfail
    app.kubernetes.io/part-of: block-copyfail-app
  name: block-copyfail
spec:
  output:
    to:
      kind: ImageStreamTag
      name: block-copyfail:latest
  runPolicy: SerialLatestOnly
  source:
    contextDir: /
    git:
      uri: https://github.com/atgreen/block-copyfail
      ref: main
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: ubi9:latest
